@hostname = betsandbox.westeurope.cloudapp.azure.com
@port = 7048
@servicename = E1
@api = api/v2.0
@myapi = api/andjela/finance/v1.0
@baseurl = {{hostname}}:{{port}}/{{servicename}}/{{api}}
@mybaseurl = {{hostname}}:{{port}}/{{servicename}}/{{myapi}}
@username = STUDENT
@password = Torek557!
@user = {{username}}:{{password}}

#### List of all Customers
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/customers
Authorization: Basic {{user}}

#### List my Ivana's Customers
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/customers?$filter=salespersonCode eq 'IVANA'
Authorization: Basic {{user}}
