@hostname = betsandbox.westeurope.cloudapp.azure.com
@port = 7048
@servicename = E1
@api = api/v2.0
@myapi = api/kristina/fm/v1.0
@baseurl = {{hostname}}:{{port}}/{{servicename}}/{{api}}
@mybaseurl = {{hostname}}:{{port}}/{{servicename}}/{{myapi}}
@username = STUDENT
@password = Torek557!
@user = {{username}}:{{password}}

### List of items
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items
Authorization: Basic {{user}}

### List of items with filter
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items?$filter=(itemCategoryCode eq 'DRESS') and (inventory gt 0)
Authorization: Basic {{user}}

### One Item
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items(1ffd020e-17ae-ec11-bb8a-000d3a299034)
Authorization: Basic {{user}}

### Item Picture Info
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items(1ffd020e-17ae-ec11-bb8a-000d3a299034)/picture
Authorization: Basic {{user}}

### Item Picture Content
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items(1ffd020e-17ae-ec11-bb8a-000d3a299034)/picture/pictureContent
Authorization: Basic {{user}}

### Item Attributes
GET http://{{mybaseurl}}/companies(27a4a34e-b3d5-ec11-9624-6045bd8fe131)/itemAttributes
Authorization: Basic {{user}}

