@hostname = betsandbox.westeurope.cloudapp.azure.com
@port = 7048
@servicename = E1
@api = api/v2.0
@myapi = api/andjela/finance/v1.0
@baseurl = {{hostname}}:{{port}}/{{servicename}}/{{api}}
@mybaseurl = {{hostname}}:{{port}}/{{servicename}}/{{myapi}}
@username = STUDENT
@password = Torek557!
@user = {{username}}:{{password}}
@currCompany = companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)
@currResouce = resources(d5fe020e-17ae-ec11-bb8a-000d3a299034)

### Resources are not part of standard apis - that's why we are using custom api.
### Note: we are using mybaseurl instead baseurl where we are addressing to api/andjela/finance/v1.0

### My list of apis
GET http://{{mybaseurl}}
Authorization: Basic {{user}}

### List of resources
GET http://{{mybaseurl}}/{{currCompany}}/resources
Authorization: Basic {{user}}

### Specific resource
GET http://{{mybaseurl}}/{{currCompany}}/{{currResouce}}
Authorization: Basic {{user}}

### Resource's image info
GET http://{{mybaseurl}}/{{currCompany}}/images(56088d2f-770c-4b90-ad12-0033ea5a61ea)
Authorization: Basic {{user}}

### Resource's image content
GET http://{{mybaseurl}}/{{currCompany}}/images(8004d519-4838-45ff-b8b3-25a4fdd0122a)/content
Authorization: Basic {{user}}

### How to call custom bound method (this example is bound to resource because it's an example of custom api and not because it makes sens posting on resource)
### Usually you would put post method on document like Sales Order.
POST http://{{mybaseurl}}/{{currCompany}}/{{currResouce}}/Microsoft.NAV.pictureContent
Authorization: Basic {{user}}

### Usually you would put post method on document like Sales Order.
POST http://{{mybaseurl}}/{{currCompany}}/{{currResouce}}/Microsoft.NAV.ping
Authorization: Basic {{user}}

### unbound action
POST http://betsandbox.westeurope.cloudapp.azure.com:7048/E1/ODataV4/Ping_Ping?company='Mina%27%27s%20web%20shop'
Authorization: Basic {{user}}