@hostname = betsandbox.westeurope.cloudapp.azure.com
@port = 7048
@servicename = E1
@api = api/v2.0
@myapi = api/andjela/finance/v1.0
@baseurl = {{hostname}}:{{port}}/{{servicename}}/{{api}}
@mybaseurl = {{hostname}}:{{port}}/{{servicename}}/{{myapi}}
@username = STUDENT
@password = Torek557!
@user = {{username}}:{{password}}

### List of apis
GET http://{{baseurl}}
Authorization: Basic {{user}}

### List of companies
GET http://{{baseurl}}/companies
Authorization: Basic {{user}}

### List of items
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items
Authorization: Basic {{user}}

### List of items with filter
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items?$filter=itemCategoryCode eq 'CHAIR' and inventory ge 0
Authorization: Basic {{user}}

### One Item
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items(1ffd020e-17ae-ec11-bb8a-000d3a299034)
Authorization: Basic {{user}}

### Item Picture Info
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items(1ffd020e-17ae-ec11-bb8a-000d3a299034)/picture
Authorization: Basic {{user}}

### Item Picture Content
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/items(1ffd020e-17ae-ec11-bb8a-000d3a299034)/picture/pictureContent
Authorization: Basic {{user}}







### My list of apis
GET http://{{mybaseurl}}
Authorization: Basic {{user}}

### List of resources
GET http://{{mybaseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/resources
Authorization: Basic {{user}}

### List of resources
GET http://{{mybaseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/resources
Authorization: Basic {{user}}

### Picture of Lina's resource
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/pictures(56088d2f-770c-4b90-ad12-0033ea5a61ea)/pictureContent
Authorization: Basic {{user}}




### Get sales Order
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/salesOrders(ec59001a-17ae-ec11-bb8a-000d3a299034)
Authorization: Basic {{user}}

### Get sales Order Lines
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/salesOrders(ec59001a-17ae-ec11-bb8a-000d3a299034)/salesOrderLines
Authorization: Basic {{user}}

### How to sent order?
POST http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/salesOrders
Authorization: Basic {{user}}
Content-Type: application/json

{
    "postingDate": "2022-05-12",
    "customerNumber": "30000"
}

### How to sent order lines?
GET http://{{baseurl}}/companies(4e7779f8-16ae-ec11-bb8a-000d3a299034)/salesOrders(901536e8-e6d1-ec11-9624-6045bd8fe131)/salesOrderLines
Authorization: Basic {{user}}

###
Content-Type: application/json

{
    "postingDate": "2022-05-12",
    "customerNumber": "30000"
}

